name: Playwright Tests with Rollback

on:
  push:
    branches:
      - main

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Ensure Playwright has execute permissions
      run: chmod +x ./node_modules/.bin/playwright

    - name: Install browsers?
      run: npx playwright install

    - name: Run Playwright tests
      env:
        BASE_URL: https://mpetruniak-3s.github.io/mpetruniak-3s.github.io
      run: npx playwright test

  deploy:
    runs-on: ubuntu-latest
    needs: playwright-tests

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Deploy to GitHub Pages
      if: success() 
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: main
        folder: .  
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Handle Playwright test failure
      if: failure() 
      run: |
        echo "Playwright tests failed, skipping deployment to GitHub Pages."
