name: Playwright Tests with Rollback

on:
  push:
    branches:
      - main

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run Playwright tests
      env:
        BASE_URL: https://mpetruniak-3s.github.io/mpetruniak-3s.github.io
      run: npx playwright test

    - name: Rollback changes if tests fail
      if: failure()
      run: |
        git config user.name "Mike Petruniak"
        git config user.email "mpetruniak@homesolutions.com"

        git revert -m 1 HEAD || true
        git push origin main --force