name: Playwright Tests with Rollback

on:
  push:
    branches:
      - main

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Ensure Playwright has execute permissions
      run: chmod +x ./node_modules/.bin/playwright

    - name: Install browsers?
      run: npx playwright install

    - name: Run Playwright tests
      env:
        BASE_URL: https://mpetruniak-3s.github.io/mpetruniak-3s.github.io
      run: npx playwright test

    - name: Rollback changes if tests fail
      if: failure()
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        LAST_COMMIT=$(git rev-parse HEAD)
        LAST_STABLE=$(git rev-list --parents -n 1 $LAST_COMMIT | awk '{print $2}')

        git reset --hard $LAST_STABLE
        git push origin main --force